AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Static build of FFmpeg/FFprobe as AWS Lambda Layer

  More information: https://github.com/jonemo/ffmpeg-aws-lambda-layer
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg-python
      Description: Bundle of static FFmpeg build and python-ffmpeg library for AWS Lambda
      ContentUri: build/layer
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: GPL-3.0-only
      RetentionPolicy: Retain

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref LambdaLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ffmpeg-lambda-layer-by-jonemo
    SemanticVersion: 4.4.1
    Description: >
      Static build of FFmpeg/FFprobe for Amazon Linux 2,
      packaged as a Lambda layer. Forked from an earlier
      version by Gojko Adzic. bundles FFmpeg static build
      by John Van Sickle. Bundles FFmpeg version 4.4.1.
    Author: Jonas Neubert
    SpdxLicenseId: GPL-3.0-only
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README-SAR.md
    Labels: ['layer', 'lambda', 'ffmpeg', 'ffprobe']
    HomePageUrl: https://github.com/jonemo/ffmpeg-aws-lambda-layer
    SourceCodeUrl: https://github.com/jonemo/ffmpeg-aws-lambda-layer
